[[bibliografia]]
= Bibliografia

[[imaginary]]
{nbsp}[1] __An Imaginary Tale: The Story of √-1 (The square root of minus one)__, Princeton Library Science Edition por Paul J. Nahin

[[attention]]
{nbsp}[2] _The Law of Attention: Nada Yoga and the Way of Inner Vigilance_ (Inner Traditions, seconda edizione, 2010) di Edward Salim Michael

http://www.innertraditions.com/the-law-of-attention.html

[[surangama]]
{nbsp}[3] _The Śūraṅgama Sūtra – With Excerpts from the Commentary by the Venerable Master Hsüan Hua (Copyright 2009 di the Buddhist Text Translation Society)_

Recentemente tradotta dal cinese dalla Commissione per la Traduzione dello
Śūraṅgama Sūtra della Buddhist Text Translation Society: Rev. Bhikṣu Heng Sure
(garante); Bhikṣu Jin Yan, Bhikṣu Jin Yong, Novizio Jin Jing, Novizio Jin Hai,
Ron Epstein, David Rounds, Joey Wei, Fulin Chang, e Laura Lin

[[shabd]]
{nbsp}[4] Da _Naam or Word -- Book two: Shabd -- The Sound Principle_ di Sant Kirpal Singh.

http://www.ruhanisatsangusa.org/naam/naam-shabd1.htm

[[deep]]
{nbsp}[5] Manoscritto non pubblicato. Cfr. _Deep Listening_, un discorso di Dharma di Jan Chozen Bays

http://www.zendust.org/audio/deep-listening
  
[[portrait]]
{nbsp}[6] Dalla poesia "`__Self Portrait__`" dell’autore, in "`__Silent Rain__`", p. 263, e in "`__Rain on the Nile__`", p. 65.

[[ensinamentos]]
{nbsp}[7] Per esempio SN 55.5:

"`Sāriputta, così è detto: '`La corrente, la corrente`'. Cosa è dunque,
Sāriputta, la corrente?`".

"`Questo Nobile Ottuplice Sentiero, venerabile signore, è la corrente;
vale a dire: retta visione, retta intenzione, retta parola, retta
azione, retti mezzi di sussistenza, retto sforzo, retta presenza
mentale, retta concentrazione`". "`Molto bene, Sāriputta, molto bene!
Questo Nobile Ottuplice Sentiero è la corrente`".
