[[domande-frequenti]]
= Domande Frequenti

_D:_ Nei Sutta o nei commentari tradizionali non ho visto menzionata da
nessuna parte questa pratica del suono del silenzio. Qual è la sua
origine?

_R:_ All’inizio questa era una pratica che il Ven. Ajahn Sumedho pensava
di aver scoperto da solo.

Viveva da undici anni nelle foreste della Thailandia, dove si tende a
fare gran parte della propria pratica formale di notte. Quelle notti
erano sempre piene di un brusio cacofonico d’insetti, così,
paradossalmente, solo nel 1977, dopo essere venuto a vivere a Londra,
iniziò a notare il suono interiore. Diventava particolarmente evidente
nel cuore della notte, nel silenzioso clima nevoso dell’inverno, e poi
un giorno divenne fortissimo, persino mentre camminava per la strada
trafficata di Haverstock Hill.

La presenza del suono era così intensa che, pur non avendo mai sentito
parlare prima di una cosa simile, iniziò a sperimentarlo come oggetto di
meditazione, scoprendo con sorpresa che si trattava di uno strumento
molto utile. Come ha scritto egli stesso nella sua Prefazione alla
recente edizione del libro “The Law of Attention”, di Edward Salim
Michael:footnoteref:[attention,_The Law of Attention: Nada Yoga and the Way of Inner Vigilance_ (Inner Traditions, seconda edizione, 2010) di Edward Salim Michael]

“Avevo scoperto questo ‘suono interiore’ molti anni prima, ma non avevo
mai sentito alcun riferimento ad esso, o letto alcunché in proposito nel
Canone in Pali. Avevo sviluppato una pratica di meditazione che si
rifaceva a questa vibrazione di fondo e sperimentato grandi benefici
nello sviluppare presenza mentale lasciando andare ogni pensiero. Era
una pratica che consentiva una prospettiva di consapevolezza
trascendente in cui si poteva riflettere sugli stati mentali che sorgono
e cessano nella coscienza”.

Egli ha anche parlato spesso di come lo sviluppo di questo ascolto
interiore abbia avuto un profondo effetto sul suo atteggiamento nei
confronti della pratica meditativa. Essendo arrivato da poco in un paese
straniero e spiccatamente non buddhista, e vivendo in una piccola casa
di una città grande e rumorosa, si accorse di provare un forte desiderio
di battere in ritirata e tornare in Thailandia alle sue amate foreste,
lontano da tutta quella gente “fastidiosa e irritante”. A un certo
punto, però, si fece strada in lui un’intuizione folgorante: piuttosto
che cercare l’isolamento fisico di _kāyaviveka_ aveva bisogno di
sviluppare l’isolamento interiore di __cittaviveka__. Trovò inoltre che
la pratica recentemente scoperta dell’ascolto interiore, dello stare con
quello che egli chiamò il suono del silenzio, fosse un sostegno ideale
per l’approccio e la qualità del cercare l’isolamento dentro di sé. Fu
un’intuizione fondamentale che gli permise di comprendere come lavorare
al meglio nel nuovo ambiente, a tal punto che quando la comunità
ricevette in dono una foresta nel West Sussex e lasciò Londra, chiamò il
nuovo monastero “Cittaviveka”, un nome che casualmente richiama quello
di Chithurst, il piccolo borgo dove questa nuova istituzione venne
fondata.

Dopo aver usato questa pratica per alcuni anni, esplorandone tutti i
risvolti e risultati su di sé, cominciò ad insegnarla alla nascente
comunità del Monastero di Cittaviveka. Era consapevole del fatto che
nelle scritture del Theravada non si trovava alcun riferimento a tale
metodo, ma sentì che, visti i risultati così benefici, perché non usarlo
comunque?

Da questo punto di vista il suo approccio fu molto simile a quello del
Ven. Mahasi Sayadaw, che negli anni cinquanta sviluppò il suo personale
metodo di meditazione di visione profonda. Un paio di elementi del suo
“Metodo Mahasi” hanno attratto critiche, poiché neanche questi sono
classici metodi di meditazione del Theravada, nella fattispecie la
pratica dell’“annotazione verbale” e l’osservazione delle sensazioni
prodotte dal respiro all’addome. Tuttavia, come lo stesso Ajahn Sumedho
ha riscontrato ascoltando il suono del silenzio, se si mettono queste
tecniche in pratica e si scopre che sono d’aiuto alla presenza mentale,
non è più saggio utilizzarle piuttosto che ignorarle solo perché magari
non sono canoniche?

Lo spirito della pratica buddhista è sempre orientato verso l’uso di
mezzi abili che aiutino a dar luogo alla liberazione, alla cessazione di
ogni insoddisfazione, di ogni dukkha, perciò se il metodo funziona
dovremmo considerarlo degno di valore.

_D:_ Questo tipo di ascolto interiore è stato usato in altre tradizioni
spirituali? È stato chiamato “nada yoga”, perciò sembra che almeno
qualche altro gruppo religioso lo abbia scoperto.

_R:_ Dopo che Ajahn Sumedho cominciò a insegnarlo, le persone
cominciarono a dirgli di averlo già conosciuto in precedenza, o
attraverso una sperimentazione personale o tramite altri gruppi con cui
avevano meditato. Un po’ alla volta si rese conto che questo metodo era
stato usato attraverso i secoli da una ricca varietà di tradizioni
spirituali.

Una delle sue prime scoperte al riguardo fu il libro di Edward Salim
Michael già menzionato. Ancora dalla sua Prefazione all’edizione del
2010:

“Ricordo di aver scoperto questo libro all’incirca 25 anni fa, alla
Summer School della Buddhist Society. Aveva in copertina un’immagine del
Buddha, e mi piaceva il titolo [che era allora ‘The Way of Inner
Vigilance’ (La Via della Vigilanza Interiore)] così iniziai a
sfogliarlo. Furono soprattutto i capitoli sul Nada Yoga a incuriosirmi…
[e] apprezzai le istruzioni di Edward Salim Michael su come integrare la
consapevolezza nella vita quotidiana”.

Le origini delle intuizioni di Michael sul nada yoga erano per lo più
frutto della sua esperienza personale, influenzata da pratiche yogiche
sia buddhiste che induiste.

Alcuni anni dopo aver incontrato “The Way of Inner Vigilance”’, e aver
iniziato a incorporare alcuni dei metodi ivi contenuti nella sua pratica
personale e nel suo insegnamento, Ajahn Sumedho si imbatté in un altro
fiorente ambito in cui questa pratica veniva utilizzata.

Era il 1991 e stava guidando un ritiro in California, presso un grande
monastero della tradizione buddhista settentrionale chiamato “The City
of Ten Thousand Buddhas” (La Città dei Diecimila Buddha). Sebbene il
ritiro fosse per lo più indirizzato al gruppo di 60 buddhisti laici che
si erano riuniti da tutti gli Stati Uniti per l’evento, era presente
anche un piccolo gruppo di monaci e monache del monastero ospitante.

All’incirca a metà ritiro Ajahn Sumedho introdusse la pratica
dell’ascolto del suono del silenzio. Un paio di giorni dopo l’abate
appena nominato del monastero, il Ven. Heng Ch’I, gli fece il seguente
commento: “Sai, credo tu ti sia imbattuto per caso nel Shūrangama
Samādhi.” Comprensibilmente, Ajahn Sumedho non era sicuro a cosa si
riferisse, perciò l’abate gli spiegò:

“Nella nostra tradizione buddhista Chan, la scrittura chiave è il Sutra
Sūrangama e in particolare gli insegnamenti di meditazione in esso
contenuti. Il Sutra illustra 25 pratiche spirituali che vari Bodhisattva
presentano al Buddha come i metodi grazie ai quali avevano raggiunto la
liberazione. Quello che il Buddha loda come il più efficace è quello di
Avalokiteshavara, il Bodhisattva femminile Guan Shi Yin. È una
meditazione basata sull’ascolto. Il cinese del Sutra può essere tradotto
in vari modi, quindi non eravamo sicuri di ciò che significasse
esattamente. Guan Yin descrive il metodo nel modo seguente:

[quote, role=quote]
____
‘Iniziai con una pratica basata sulla natura
illuminata dell’ascolto. Per prima cosa ho ridiretto il mio ascolto
all’interno per entrare nella corrente dei saggi…

Con i mezzi che ho descritto, ho varcato la soglia della facoltà
dell’udito e perfezionato l’illuminazione interiore del samādhi. La mia
mente che un tempo dipendeva dagli oggetti percepiti sviluppò
auto-padronanza e agio. Entrando nella corrente dei risvegliati ed
entrando in samādhi, divenni pienamente risvegliata. Questo perciò è il
metodo migliore’.footnoteref:[surangama,_The Śūraṅgama Sūtra – With Excerpts from the Commentary by the Venerable Master Hsüan Hua (Copyright 2009 di the Buddhist Text Translation Society)_]
____

Shifu [il Ven.Maestro Hsüan Hua, l’abate fondatore e insegnante] era
solito cercare di spiegarci cosa ciò significasse dicendoci cose come:

[quote, role=quote]
____
‘Ascoltare saggiamente è ascoltare dentro, non fuori,
senza permettere alla mente di inseguire i suoni. Il Buddha aveva detto
prima nel Sutra di non seguire le sei facoltà [occhio, orecchio, naso,
lingua, corpo e mente] e di non farsi influenzare da loro. Ciò che
dovete fare è dirigere il vostro udito nella direzione opposta per
ascoltare la vostra vera natura. Invece di ascoltare i suoni esterni, vi
focalizzate interiormente sul vostro corpo e sulla vostra mente,
smettete di cercare al di fuori di voi, e capovolgete la luce della
vostra attenzione affinché splenda al vostro interno.’footnoteref:[surangama]
____

Noi gli chiedevamo cosa intendesse per ‘dirigere il vostro udito nella
direzione opposta’’ e lui ci diceva cose come: ‘Voltate indietro l’udito
per ascoltare l’organo dell’orecchio, e naturalmente non si tratta
dell’orecchio fisico… capite?!’. Ma ovviamente per lo più non capivamo…

Quindi ora, con questo metodo dell’ascolto interiore che hai insegnato
negli ultimi giorni, inizia tutto a diventare molto più chiaro,
specialmente frasi come, ‘la corrente dei risvegliati’. Finalmente
capisco quale sia la pratica che è stata così importante per la nostra
tradizione. Grazie per aver risolto il mistero di cosa significassero
quelle parole, e grazie per averci insegnato come usarla!”.

Con il passare del tempo spuntarono altre persone che descrissero
pratiche e insegnamenti che impiegano in modo simile questo stesso suono
interiore. In anni recenti la maestra zen Chozen Bays, del Great Vow Zen
Monastery (Monastero del Grande Voto) in Oregon, ha scritto come le
sembri che proprio questo suono, e il profondo ascolto che se ne può
fare, siano la base del famoso koan di Hakuin Ekaku: “Due mani
applaudono e c’è un suono; (ma) qual è il suono di una mano sola?”:

“In occidente questo koan, il Suono di una Mano Sola, è stato
banalizzato, ma il suo vero significato è molto profondo. Il koan è una
domanda alla quale non si può rispondere con il nostro solito metodo:
attraverso il pensiero. Le si può rispondere solo attraverso un
non-pensare. È una domanda che ci richiede di impegnarci in un ascolto
profondo, di ascoltare come non abbiamo mai fatto prima, di ascoltare
non solo con le nostre orecchie ma con la totalità del nostro essere,
con i nostri occhi, la nostra pelle, le nostre ossa e il nostro cuore.

L’ascolto profondo richiede completa ricettività. Questo significa che
da noi non viene prodotto nulla, non ci sono fuoriuscite. L’ascolto
profondo ci chiede di acquietare il corpo, la parola e la mente. I
nostri pensieri devono essere silenziosi. Impossibile, potreste dire.
Non è impossibile, non quando state ascoltando così attentamente che
persino i suoni dei vostri pensieri sono di ostacolo al vostro ascolto.
Questo è ascolto concentrativo, totale assorbimento nel suono”.footnoteref:[deep,Manoscritto non pubblicato. Cfr. _Deep Listening_, un discorso di Dharma di Jan Chozen Bays]

All’insaputa di Ajahn Sumedho, dunque, tale pratica faceva parte da
lungo tempo della tradizione buddhista, e questo nonostante non ci sia
alcun riferimento ad essa nei sutta in pali o nei commentari classici
del Buddhismo meridionale, come il __Visuddhimagga__.

In aggiunta a questi precedenti nel mondo buddhista, la pratica
dell’ascolto del suono interiore gioca un ruolo significativo in molte
altre tradizioni spirituali. Ad esempio, nel movimento spirituale del
Sant Mat, che ha tratto origine dalla tradizione Sikh, la “Meditazione
sulla Luce e sul Suono Interiori” include la pratica dell’ascolto della
Corrente del Suono, chiamata __Shabd, Naam__, ovvero la “Parola
manifestante Dio”.

In questa e in molte altre scuole il suono interiore è considerato di
natura intrinsecamente divina, diversamente dalla tradizione buddhista,
che non vi accorda di per sé un particolare significato spirituale.

Lo Shabd, variamente denominato la Corrente Sonora della Vita, il Suono
Interiore, o la Corrente del Suono, è considerato l’essenza esoterica di
Dio accessibile a tutti gli esseri umani, questo secondo gli
insegnamenti del Sentiero dello Shabd di Eckankar, del Sant Mat e dello
Surat Shabd Yoga.

Nelle parole di quest’ultima tradizione, il suono interiore è
considerato in questo modo:

“È l’Essenza dell’Assoluto Essere Supremo, cioè la forza dinamica di
energia creativa che fu emessa, come vibrazione sonora, dall’Essere
Supremo nell’abisso dello spazio all’alba della manifestazione
dell’universo, e che viene propagata attraverso le epoche a racchiudere
tutte le cose che costituiscono e abitano l’universo”.footnoteref:[shabd,Da _Naam or Word -- Book two: Shabd -- The Sound Principle_ di Sant Kirpal Singh.]

Lo Surat Shabd Yoga descrive il suo scopo come l’“Unione dell’Anima con
l’Essenza dell’Assoluto Essere Supremo”. Altre espressioni per questa
pratica includono il Sentiero della Luce e del Suono, il Viaggio
dell’Anima, e lo Yoga della Corrente del Suono.

Il suono interiore è stato sviluppato come sentiero spirituale o punto
di riferimento anche in altre tradizioni. Nelle scritture e opere
filosofiche sotto elencate si dice che gli siano stati attributi i
seguenti nomi:

* _Naad, Akash Bani e Sruti,_ nei Veda.
* Nada e __Udgit__, nelle Upanishad.
* La Musica delle Sfere, negli insegnamenti di Pitagora.
* __Sraosha__, in Zoroastro.
* __Kalma e Kalam-i-Qadim__, nel Corano.
* Naam, _Akhand Kirtan_ e __Sacha Shabd__, nel Guru Granth Sahib.

_D:_ Quando seguo le tue istruzioni per ascoltare il suono del silenzio,
mi sembra che assomigli un po’ a un acufene, un fischio nelle orecchie.
C’è una relazione tra i due? Ho sempre pensato che quel suono interiore
fosse un po’ fastidioso; ora che mi hai incoraggiato ad ascoltarlo, ecco
che all’improvviso ho iniziato a rallegrarmi della sua presenza. Cosa
sta succedendo?

_R:_ Nell’edilizia, quando in un progetto sul quale si sta lavorando si
viene confrontati con un’anomalia inevitabile - come ad esempio una
trave a sbalzo che spunta fuori in una stanza di una vecchia casa, o una
roccia inamovibile al centro di un giardino – c’è questa antica regola:
“Se non la potete nascondere, fatela diventare una caratteristica
interessante”.

Se non proveniamo da una tradizione che considera il suono-nada come una
qualità elevata e lo abbiamo invece sempre giudicato un’intrusione
fastidiosa, suggerirei che la maggior parte di noi può cambiare il
proprio atteggiamento nei suoi confronti in modo simile a quell‘aforisma
edile. E come nella tua descrizione, questo è proprio quello che hai
scoperto corrispondere al vero: ciò che era motivo d’irritazione può
diventare una presenza gradita.

Per la grande maggioranza delle persone non è detto che il suono-nada
sia una qualità fastidiosa o intrusiva. Anzi, come hai scoperto tu,
persino nello spazio di pochi giorni o poche ore, e con solo un piccolo
cambio di atteggiamento, quel masso seccante che stava rovinando il tuo
prato può essere trasformato in una presenza gradevole e rallegrante.

Durante un seminario di un giorno in cui stavo insegnando proprio su
questo tema, una donna disse al gruppo che ora che poteva relazionarsi
al suono come a un supporto spirituale, considerandolo come un utile
compagno, stava provando sensazioni di rabbia per tutti i soldi che
aveva sprecato andando invano da così tanti specialisti. “Sono
veramente arrabbiata!”, disse ridendo, “ma è un tale sollievo non
dover più considerare quel suono un problema che penso mi passerà!”.

A tal riguardo, Chozen Bays ha scritto:

[quote, role=quote]
____
“Molti vengono da me lamentando che quando meditano
sono infastiditi da un forte fischio o ronzio nelle orecchie. Sono
angosciati perché il dottore ha detto loro che hanno una malattia
incurabile, l’acufene. Quando indago meglio scopro che non si tratta di
acufene, ma che hanno iniziato a udire il suono che nel buddhismo del
Theravada è chiamato il suono nada. Altri lo hanno chiamato il suono
della natura, il suono di tutte le cose viventi o il suono tra i suoni.
Alcuni compositori hanno detto che è il “La”, la nota fondamentale e
che quando lo pronunciamo siamo in risonanza con il suono essenziale di
tutta l’esistenza”.footnoteref:[deep]
____

In una piccola percentuale di persone, in genere per qualche ragione
biologica, il suono interiore è talmente forte da risultare oppressivo o
insopportabile. In questi casi è improbabile che questo tipo di pratica,
l’ascolto interiore, sia d’aiuto come meditazione, dato che l’intensità
soggettiva del suono lo rende inutilizzabile come oggetto volto a
incoraggiare pace e chiarezza. Allo stesso modo, se avete un enfisema,
con problemi di respirazione dolorosi e imprevedibili, è improbabile che
la pratica della consapevolezza del respiro sia per voi uno strumento
molto utile.

_D:_ Dunque che cos’è in realtà? Cosa produce questo suono? Alcune
tradizioni lo considerano una presenza divina, ma un fisiologo potrebbe
dire che si tratta semplicemente dell’effetto elettrico di impulsi
neuronali che esplodono nelle orecchie. Che cosa __è__?

_R:_ Per quanto concerne la pratica che ho qui descritto, in realtà non
ha nessuna importanza.

Una persona dice: “È l’Essenza dell’Assoluto Essere Supremo”,
un’altra, “È solo il brusio del sistema nervoso”. Pitagora potrebbe
dire: “Dato che il sole, la luna e i pianeti producono ognuno una
vibrazione particolare basata sulla propria rotazione, noi sentiamo
questa Musica delle Sfere, che non è udibile esternamente dall’orecchio
umano”, e un praticante di hatha yoga: “No, è la risonanza della
vostra energia vitale, del vostro __prana__, mentre attraversa i sette
chakra.” “È la presenza sentita, percepibile del vostro sistema
energetico psico-fisico.” “È il Canto della Talità”. “No! È…”. Si
potrebbe andare avanti all’infinito.

Il punto non è teorizzare, formulando giudizi irremovibili di ben poca
utilità, quanto piuttosto usare le qualità benefiche di questa
vibrazione onnipresente e universale per aiutarci a risvegliarci, a
essere saggi e in pace.

È come per il respiro. Ci si può relazionare al respiro secondo una
modalità scientifica occidentale, per cui i polmoni traggono
semplicemente l’energia necessaria dall’ossigeno nell’atmosfera
espellendo le scorie di anidride carbonica, oppure si può pensare al
respiro come a una qualità cosmica, metafisica, il prāna (la parola
sanscrita per “respiro”) dell’Universo, che si muove in cicli
inesorabili. Indipendentemente dal significato che gli si attribuisce -
cosmologico o meccanico – si può osservare il respiro e utilizzarlo come
supporto alla concentrazione e alla consapevolezza.

Lo stesso vale per il nada yoga, e perciò è questa l’attitudine che io
incoraggio sempre. A prescindere da ciò che è “in realtà” (sempre che
in tale contesto si possa usare quest’espressione nel suo corretto
significato) ne possiamo fare uso, e i risultati di quell’utilizzo sono
reali e del tutto tangibili.

_D:_ Ho sentito dire che se si può udire questo suono significa che si è
illuminati. È vero? Un mio amico è andato a un week-end di meditazione
molto costoso in cui ha imparato questo metodo. Può anche avergli fatto
del bene, ma mi è sembrato un po’ esagerato parlare di illuminazione.
Cosa ne pensi?

_R:_ Penso che quest’insegnamento sia inestimabile, ma non valga la pena
pagare 5.000 dollari per un fine settimana! Almeno questo è il prezzo
che ho visto alcuni anni fa per un simile evento in America.

Se potete udire il suono-nada questo decisamente NON significa che siete
illuminati, almeno non secondo il modo in cui il termine viene
utilizzato nel mondo buddhista. Essere illuminati, per usare le
definizioni classiche buddhiste, vuol dire che il vostro cuore e la
vostra mente sono irreversibilmente liberi da ogni avidità, odio e
ignoranza, e incapaci di attitudini egoiste di qualsiasi sorta. Gli
esseri illuminati hanno un cuore completamente puro, non agiranno mai
con inganno, violenza o disonestà, né indulgeranno nei sensi. Essi
dimorano in uno stato di pace, gioia e indipendenza incrollabili. Ed è
altamente improbabile che si farebbero pagare una cifra simile per i
propri insegnamenti.

Il suono-nada è una naturale qualità dell’esperienza alla quale si può
prestare ascolto e, se usato saggiamente e per un lungo periodo di
tempo, può essere un mezzo abile in grado di favorire un’autentica
liberazione.

È naturale che quando le persone hanno avuto una bella esperienza siano
entusiaste di condividerla con altri, ma potrebbero enfatizzare le
proprie affermazioni a causa di una percezione errata.

Allo stesso modo, avendo tratto molti benefici per se stesse, spesso
desiderano scoprire nell’esperienza un significato più profondo, oppure
ottenerne una qualche conferma dall’esterno. A tal riguardo, capita a
volte che in ambito del Theravada chi è stato istruito in questa pratica
dell’ascolto interiore esclami cose come: “Sai che i discepoli del
Buddha erano chiamati __Sāvaka-Sangha__, ‘La Comunità di Coloro che
Ascoltano’! Deve voler dire che erano coloro che potevano udire il Suono
Interiore!”. Oppure, con una derivazione etimologica ancora più dubbia:
“Sai come il termine _Sotāpanna_ [che significa uno che ha raggiunto il
primo stadio dell’illuminazione] viene sempre tradotto come: ‘Colui che
è entrato nella __corrente__’. Beh, io credo che sia stato considerato
erroneamente ‘__sota__’. Sì, ‘sota’ vuol dire ‘corrente’, ma anche
‘l’orecchio, l’organo dell’udito’, scritto esattamente allo stesso modo!
Quindi ciò che significa veramente è: ‘Colui che ha realizzato il Dhamma
per il tramite della facoltà dell’udito’. Perciò chi è capace di
ascoltare il suono-nada è in realtà un __Sotāpanna__!”.

Sbagliato di nuovo! Si tratta ancora una volta di una pia illusione,
perché non è questo il significato di questo particolare “sota”, come
è del resto confermato da molti altri insegnamenti.footnoteref:[ensinamentos,Per esempio SN 55.5:
"`Sāriputta, così è detto: '`La corrente, la corrente`'. Cosa è dunque,
Sāriputta, la corrente?`".
"`Questo Nobile Ottuplice Sentiero, venerabile signore, è la corrente;
vale a dire: retta visione, retta intenzione, retta parola, retta
azione, retti mezzi di sussistenza, retto sforzo, retta presenza
mentale, retta concentrazione`". "`Molto bene, Sāriputta, molto bene!
Questo Nobile Ottuplice Sentiero è la corrente`".]

Inoltre, anche se si potesse sostenere in modo convincente come
interpretazione “Colui che è entrato tramite l’ascolto”, ci vorrebbe
molto più che il semplice essere in grado di sentire il suono del
silenzio perché l’esperienza potesse essere considerata come un segno
dell’aver raggiunto il primo stadio dell’illuminazione. Essere un
Sotāpanna significa che il cuore e la mente sono completamenti liberi
dall’identificazione con il corpo e la personalità, non c’è alcun
attaccamento o confusione rispetto a convenzioni sociali e religiose.
Infine, colui che ha raggiunto questa realizzazione è andato
completamente al di là di ogni possibile dubbio riguardo a cosa sia o
non sia il sentiero per la liberazione. Questa profondità di risveglio è
assolutamente al di là di qualsiasi benedizione spirituale derivante
dall’essere semplicemente capaci di udire il suono-nada.

Allo stesso modo ho anche sentito persone fare affermazioni del tipo:
“È il suono dell’Incondizionato,” oppure “È il Canto di Ciò Che Non
Muore”, e anch’io ne ho fatte alcune dello stesso tenore:

[quote, role=quote]
____
Un canto di Talità chiaro e luminoso, +
l’infinita pace interiore della luce, +
la cui presenza incessante romba +
oceanica alle sue sponde.footnote:[portrait,Dalla poesia "`__Self Portrait__`" dell’autore, in "`__Silent Rain__`", p. 263, e in "`__Rain on the Nile__`", p. 65.]
____

L’errore subentra quando presumiamo che essere in grado di udire il
suono interiore voglia dire avere davvero trovato Ciò Che Non Muore. Non
è così. Tutto ciò di cui possiamo essere certi è che abbiamo scoperto un
ronzio nelle nostre orecchie. Ancora una volta, sebbene queste possano
essere espressioni poetiche e ispirate, valide metafore della Verità,
secondo la prospettiva buddhista questa ulteriore presunzione di
conseguimento è una seria sopravvalutazione della questione.

Dopotutto, considerate coloro che pensando si trattasse di acufene lo
hanno curato come un disturbo fastidioso: potrebbero essere ben lontani
da ogni tipo di realizzazione spirituale e, per di più, non hanno
neanche dovuto pagare un sacco di soldi per riuscire a sentirlo.

Come accennato prima, almeno secondo una prospettiva buddhista,
ascoltare il suono del silenzio può essere un mezzo abile di _supporto_
alla liberazione, ma il fatto di sentirlo _non costituisce_ la
liberazione.

Il suono-nada ha attributi che lo rendono un simbolo ideale del Dhamma
trascendente, Ciò Che Non Muore, ma è fondamentale tenere a mente che
queste qualità sono simboli nella sfera dei sensi di ciò che è
intrinsecamente al di là della sfera sensoriale. Questo ci aiuta ad
apprezzarne la presenza, senza cadere però nell’errore di confondere un
utile cartello stradale con quello che vuol dire arrivare alla fine del
viaggio.

_D:_ Se non riesco a sentirlo, percepirlo, vederlo o altro… allora che
fare?

_R:_ Beh, come si è detto, “L’oro è là dove lo trovi”, per cui se non
riesci a discernere questa vibrazione in nessuna maniera forse hai
bisogno di scavare da qualche altra parte. Questo vuol dire usare un
metodo di meditazione che sia più adatto alle tue caratteristiche, come
la consapevolezza del respiro o la meditazione di gentilezza amorevole,
oppure puoi usare un mantra.

Prima di rinunciarci, però, ci sono un paio di semplici tentativi che
puoi fare per aiutarti a trovarlo e poi per sviluppare la capacità di
usarlo. Innanzitutto prova semplicemente a metterti le dita nelle
orecchie. Può sembrare un metodo un po’ grossolano e ovviamente non è
raccomandabile per una pratica di lungo termine, ma può essere un buon
modo per stabilire un contatto iniziale, escludendo tutti i suoni
esterni il più completamente possibile e poi vedendo ciò che rimane
nell’udito.

In secondo luogo, e questo è un po’ più impegnativo, la prossima volta
che ti fai un bagno o vai in piscina, metti le orecchie sott’acqua e
rimani immobile. Ancora una volta, volgi la tua attenzione alla facoltà
dell’udito e semplicemente ascolta. Va da sé che se ti trovi in una
piscina pubblica rumorosa è improbabile che sentirai molta differenza,
ma se puoi sperimentarlo in un ambiente tranquillo può essere
un’introduzione illuminante al suono interiore.
